FROM alpine
RUN apk add --no-cache lighttpd
WORKDIR /var/www/localhost/htdocs/
ADD index-gcp.html index.html
ADD images/gcp.png images/gcp.png
CMD ["lighttpd", "-f", "/etc/lighttpd/lighttpd.conf", "-D"] 
